---
services:
  docker-exporter:
    container_name: docker-exporter
    image: ageres210784/docker-exporter:latest
    restart: always
    build:
      context: .
      target: build
    ports:
      - 8080:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      EXPORTER_MODE: swarm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: any
